# Site settings
author: Juny McArdle
title: The Coding Mom
header-img: img/home-bg.png
email: juny.mcardle@gmail.com
copyright_name: Juny McArdle
description: > # this means to ignore newlines until "baseurl:"
  My journey from changing diapers to changing syntax...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  junymc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
